### ISSUE TITLE
Relax dependency version constraints

### ISSUE THREAD

**Issue by alexkyllo** [dodopizza/sqlalchemy-kusto#10]
Hello,

Thank you for writing this package. However, I installed it and noticed that your setup.py pins very specific, older versions of azure-kusto-data (of which the latest version is 3.1.1) and sqlalchemy (latest 1.4.40). My pip is yelling at me that I have incompatible versions of these packages and I don't know whether these are real incompatibilities or not. Could you please relax the version constraints in your setup.py to provide a range of compatible versions of these dependencies?

```
REQUIREMENTS = [
    "azure-kusto-data==2.1.1",
    "sqlalchemy==1.3.24",
]
```

**Comment by Ceridan** [comment]
Hello Alex,

Thank you for creating this issue. When this library was created our main goal was to be compatible with [apache/superset](), this is why we freeze the same versions. But now we are working on supporting the latest versions of `sqlalchemy` and `azure-kusto-data`. 
PR #11 should resolve the issue.

**Comment by Ceridan** [comment]
@alexkyllo,

We have built a new version of the library with relaxed dependencies. You may give it a try:

```shell
pip install sqlalchemy-kusto==2.0.0
```

**Comment by alexkyllo** [comment]
> @alexkyllo,
> 
> We have built a new version of the library with relaxed dependencies. You may give it a try:
> 
> ```shell
> pip install sqlalchemy-kusto==2.0.0
> ```

Thank you so much for the quick fix!
